---
apiVersion: v1
kind: Service
metadata:
  name: send-notification
  labels:
    app: office-space
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: office-space
    tier: notification
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: send-notification
  labels:
    app: office-space
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: office-space
        tier: notification
    spec:
      containers:
        - image: sunilvb/send-notification:v1
          imagePullPolicy: Always
          name: send-notification
          env:
            - name: GMAIL_SENDER_USER
              value: 'sunilvb@gmail.com'
            - name: GMAIL_SENDER_PASSWORD
              value: 'Sunder76$#'
            - name: EMAIL_RECEIVER
              value: 'sunilvb@gmail.com'
            - name: OPENWHISK_API_URL_SLACK
              value: ''
            - name: NOTIFICATION_MESSAGE
              value: 'Your balance is over $50,000.00'
            - name: OPENWHISK_API_URL_EMAIL
              value: ''
          ports:
            - containerPort: 8080
